### ISSUE TITLE
long haul test error : An out-point points to a transaction that does not exist yet.

### ISSUE THREAD

**Issue by Kangmo** [ScaleChain/scalachain#144]
An output pointed by an out-point spent by the in-point points to a transaction that does not exist yet.

repro :
In ubuntu env, run.sh 0, run.sh 1, ..., run.sh 4 in five terminal tabs.
'run.sh 1' tab shows the following error.

log:
```
16:53:12.801 [nioEventLoopGroup-4-1] ERROR i.s.blockchain.net.NodeClientHandler - io.scalechain.blockchain.ChainException: An output pointed by an out-point(OutPoint(transactionHash=Hash("9c30d9da0dc4a47b10d1744351aa427e158181a6bef03f806c5c1ce1818d28db"), outputIndex=0)) spent by the in-point(InPoint(transactionHash=Hash("6d53f697ee4b8e8d3a5f2c3378132b92d5d22cb305df33c4def5cbfc0d5cbaf9"), inputIndex=0)) points to a transaction that does not exist yet.. Stack : io.scalechain.blockchain.ChainException: An output pointed by an out-point(OutPoint(transactionHash=Hash("9c30d9da0dc4a47b10d1744351aa427e158181a6bef03f806c5c1ce1818d28db"), outputIndex=0)) spent by the in-point(InPoint(transactionHash=Hash("6d53f697ee4b8e8d3a5f2c3378132b92d5d22cb305df33c4def5cbfc0d5cbaf9"), inputIndex=0)) points to a transaction that does not exist yet.
	at io.scalechain.blockchain.chain.TransactionMagnet.markOutputSpent(TransactionMagnet.kt:100)
	at io.scalechain.blockchain.chain.TransactionMagnet.attachTransactionInput(TransactionMagnet.kt:261)
	at io.scalechain.blockchain.chain.TransactionMagnet.attachTransactionInputs(TransactionMagnet.kt:279)
	at io.scalechain.blockchain.chain.TransactionMagnet.attachTransaction(TransactionMagnet.kt:299)
	at io.scalechain.blockchain.chain.BlockMagnet.attachBlock(BlockMagnet.kt:97)
	at io.scalechain.blockchain.chain.BlockMagnet.attachBlocksAfter(BlockMagnet.kt:167)
	at io.scalechain.blockchain.chain.BlockMagnet.reorganize(BlockMagnet.kt:203)
	at io.scalechain.blockchain.chain.Blockchain.putBlock(BlockChain.kt:213)
	at io.scalechain.blockchain.chain.processor.BlockProcessor.acceptBlock(BlockProcessor.kt:139)
	at io.scalechain.blockchain.net.handler.BlockMessageHandler.handle(BlockMessageHandler.kt:43)
	at io.scalechain.blockchain.net.ProtocolMessageHandler.handle(ProtocolMessageHandler.kt:59)
	at io.scalechain.blockchain.net.NodeClientHandler.channelRead0(NodeClientHandler.kt:25)
	at io.scalechain.blockchain.net.NodeClientHandler.channelRead0(NodeClientHandler.kt:13)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1371)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1234)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1283)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
 
```

**Comment by Kangmo** [comment]
Tried running in different folders for each process, but the issue still reproed.

**Comment by Kangmo** [comment]
1st analysis of the root cause:
The exception was raised during the validation of transactions in a block while block reorganization was in progress.

`	at io.scalechain.blockchain.chain.BlockMagnet.reorganize(BlockMagnet.kt:203)
`

**Comment by Kangmo** [comment]
reproed in Mac as well

scalechain.conf
```
scalechain {
  api {
    port = 8080
    user = "user"
    password = "eifowefowfnoinfoion2ivnvn23f"
  }
  p2p {
    port = 7643
    peers = [
      { address:"127.0.0.1", port:"7643" }
      { address:"127.0.0.1", port:"7644" }
      { address:"127.0.0.1", port:"7645" }
      { address:"127.0.0.1", port:"7646" }
      { address:"127.0.0.1", port:"7647" }
    ]
  }
  network {
    name = "mainnet"
  }
  mining {
    address = "1xxxxxxxxxxxxxxxxxxxxxxxxxxxx"
  }
}

```


screen output:
```
19:23:18.847 [Thread-0] INFO  i.s.b.chain.mining.BlockMining - Coin Miner stats : Candidate Tx Count : 0, Valid Tx Count : 0, Attachable Tx Count : 0
19:23:19.400 [nioEventLoopGroup-4-1] TRACE i.s.b.n.handler.BlockMessageHandler - <P2P> Received a block. Hash : Hash("002d122651ae5ffee34712641a91318e583a37e7118648e1fac123cdc1b76519"), Header : BlockHeader(version=1, hashPrevBlock=Hash("003708fc65b0081769caf167c78bf910a50a1be96d5499a565aca3c0f66c4d83"), hashMerkleRoot=Hash("9b3198757805b1f2cbe9107509585363a93ef96440b0750ac3b72a6a29c9cfe6"), timestamp=1669112598L, target=10L, nonce=77L)
19:23:19.402 [nioEventLoopGroup-4-1] INFO  i.s.blockchain.chain.Blockchain - Block reorganization started. Original Best : (Hash("002d4a48b1a038ccb974cf83e74550314c7c6bef650104047462871ea8994016"),BlockInfo(height=4, chainWork=8796093026304, nextBlockHash=null, transactionCount=1, status=0, blockHeader=BlockHeader(version=1, hashPrevBlock=Hash("0022e4f0e7a9fd0cc1f9c8b43da50b6af98138f377777ceae36c6b7f08f85a43"), hashMerkleRoot=Hash("966b25c6922798cb443dea8699132f52309c7338a3a420f1fd6aa7eedf60d24d"), timestamp=1669112531L, target=10L, nonce=74L), blockLocatorOption=FileRecordLocator(fileIndex=0, recordLocator=RecordLocator(offset=3364, size=197)))), The Best (Hash("002d122651ae5ffee34712641a91318e583a37e7118648e1fac123cdc1b76519"),BlockInfo(height=6, chainWork=8796093028352, nextBlockHash=null, transactionCount=1, status=0, blockHeader=BlockHeader(version=1, hashPrevBlock=Hash("003708fc65b0081769caf167c78bf910a50a1be96d5499a565aca3c0f66c4d83"), hashMerkleRoot=Hash("9b3198757805b1f2cbe9107509585363a93ef96440b0750ac3b72a6a29c9cfe6"), timestamp=1669112598L, target=10L, nonce=77L), blockLocatorOption=FileRecordLocator(fileIndex=0, recordLocator=RecordLocator(offset=3561, size=197))))
19:23:19.410 [nioEventLoopGroup-3-3] TRACE i.s.b.n.handler.BlockMessageHandler - <P2P> Received a block. Hash : Hash("002d122651ae5ffee34712641a91318e583a37e7118648e1fac123cdc1b76519"), Header : BlockHeader(version=1, hashPrevBlock=Hash("003708fc65b0081769caf167c78bf910a50a1be96d5499a565aca3c0f66c4d83"), hashMerkleRoot=Hash("9b3198757805b1f2cbe9107509585363a93ef96440b0750ac3b72a6a29c9cfe6"), timestamp=1669112598L, target=10L, nonce=77L)
19:23:19.410 [nioEventLoopGroup-4-1] TRACE io.scalechain.wallet.Wallet - <Wallet unregister tx:Hash("966b25c6922798cb443dea8699132f52309c7338a3a420f1fd6aa7eedf60d24d")> started.
19:23:19.411 [nioEventLoopGroup-4-1] TRACE io.scalechain.wallet.Wallet - <Wallet unregister tx:Hash("8050b71a23d0a8ada8529a3c2c286f7d96b7710d380ba6f442faccc6e50eb9a2")> started.
19:23:19.411 [nioEventLoopGroup-4-1] TRACE io.scalechain.wallet.Wallet - <Wallet unregister tx:Hash("911a01f9081772731e971c3a4e0896521610375d32c9a1fd5c8c87d0ba49e388")> started.
19:23:19.411 [nioEventLoopGroup-4-1] TRACE io.scalechain.wallet.Wallet - <Wallet unregister tx:Hash("309e61aded0d4efb8f6e717b11b88ae0267a954380a0d506afdf3ddd3254faf9")> started.
19:23:19.412 [nioEventLoopGroup-4-1] TRACE io.scalechain.wallet.Wallet - <Wallet register tx:Hash("309e61aded0d4efb8f6e717b11b88ae0267a954380a0d506afdf3ddd3254faf9")> started.
19:23:19.412 [nioEventLoopGroup-4-1] WARN  i.s.b.chain.TransactionMagnet - An output pointed by an out-point(OutPoint(transactionHash=Hash("97ce8beae80e220b675de2a20b3661b8b217b4ebc1f9960b5d3ca5d7ae5db009"), outputIndex=0)) spent by the in-point(InPoint(transactionHash=Hash("e423e0b6d613cdb47254966c71ccd0d2442c12a3b75a604c0d0583f32b547577"), inputIndex=0)) points to a transaction that does not exist yet.
19:23:19.412 [nioEventLoopGroup-4-1] ERROR i.s.blockchain.net.NodeClientHandler - io.scalechain.blockchain.ChainException: An output pointed by an out-point(OutPoint(transactionHash=Hash("97ce8beae80e220b675de2a20b3661b8b217b4ebc1f9960b5d3ca5d7ae5db009"), outputIndex=0)) spent by the in-point(InPoint(transactionHash=Hash("e423e0b6d613cdb47254966c71ccd0d2442c12a3b75a604c0d0583f32b547577"), inputIndex=0)) points to a transaction that does not exist yet.. Stack : io.scalechain.blockchain.ChainException: An output pointed by an out-point(OutPoint(transactionHash=Hash("97ce8beae80e220b675de2a20b3661b8b217b4ebc1f9960b5d3ca5d7ae5db009"), outputIndex=0)) spent by the in-point(InPoint(transactionHash=Hash("e423e0b6d613cdb47254966c71ccd0d2442c12a3b75a604c0d0583f32b547577"), inputIndex=0)) points to a transaction that does not exist yet.
	at io.scalechain.blockchain.chain.TransactionMagnet.markOutputSpent(TransactionMagnet.kt:100)
	at io.scalechain.blockchain.chain.TransactionMagnet.attachTransactionInput(TransactionMagnet.kt:261)
	at io.scalechain.blockchain.chain.TransactionMagnet.attachTransactionInputs(TransactionMagnet.kt:279)
	at io.scalechain.blockchain.chain.TransactionMagnet.attachTransaction(TransactionMagnet.kt:299)
	at io.scalechain.blockchain.chain.BlockMagnet.attachBlock(BlockMagnet.kt:97)
	at io.scalechain.blockchain.chain.BlockMagnet.attachBlocksAfter(BlockMagnet.kt:167)
	at io.scalechain.blockchain.chain.BlockMagnet.reorganize(BlockMagnet.kt:203)
	at io.scalechain.blockchain.chain.Blockchain.putBlock(BlockChain.kt:215)
	at io.scalechain.blockchain.chain.processor.BlockProcessor.acceptBlock(BlockProcessor.kt:139)
	at io.scalechain.blockchain.net.handler.BlockMessageHandler.handle(BlockMessageHandler.kt:43)
	at io.scalechain.blockchain.net.ProtocolMessageHandler.handle(ProtocolMessageHandler.kt:59)
	at io.scalechain.blockchain.net.NodeClientHandler.channelRead0(NodeClientHandler.kt:25)
	at io.scalechain.blockchain.net.NodeClientHandler.channelRead0(NodeClientHandler.kt:13)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.handler.ssl.SslHandler.unwrap(SslHandler.java:1371)
	at io.netty.handler.ssl.SslHandler.decodeJdkCompatible(SslHandler.java:1234)
	at io.netty.handler.ssl.SslHandler.decode(SslHandler.java:1283)
	at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:507)
	at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:446)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:276)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:166)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:986)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:833)
 
19:23:19.413 [nioEventLoopGroup-3-3] TRACE i.s.blockchain.chain.Blockchain - Duplicate block was ignored. Block hash : Hash("002d122651ae5ffee34712641a91318e583a37e7118648e1fac123cdc1b76519")
19:23:19.853 [Thread-0] INFO  i.s.b.chain.mining.BlockMining - Coin Miner stats : Candidate Tx Count : 0, Valid Tx Count : 0, Attachable Tx Count : 0
```
