### ISSUE TITLE
RPC calls such as getrawtransaction hangs during IBD

### ISSUE THREAD

**Issue by Kangmo** [ScaleChain/scalachain#34]
## problem

RPC calls such as getrawtransaction hangs during IBD(Initial block download process).
## root cause

During the IBD process, we have many blocks coming from peers. These blocks are sent to block processor, but for block processor, it takes time to verify signatures of transactions, as signature verification is a costly operation.

An evidence of this is, whenever we hit this issue, jstack shows that we are verifying transaction signatures.

```
"ScaleChainPeer-akka.actor.default-dispatcher-20" #68 prio=5 os_prio=31 tid=0x00007fcb01594800 nid=0x9403 runnable [0x0000700003253000]
   java.lang.Thread.State: RUNNABLE
        at org.spongycastle.math.ec.custom.sec.SecP256K1Field.multiply(SecP256K1Field.java:78)
        at org.spongycastle.math.ec.custom.sec.SecP256K1Point.twice(SecP256K1Point.java:226)
        at org.spongycastle.math.ec.custom.sec.SecP256K1Point.twicePlus(SecP256K1Point.java:275)
        at org.spongycastle.math.ec.ECAlgorithms.implSumOfMultiplies(ECAlgorithms.java:480)
        at org.spongycastle.math.ec.ECAlgorithms.implSumOfMultiplies(ECAlgorithms.java:434)
        at org.spongycastle.math.ec.ECAlgorithms.implSumOfMultipliesGLV(ECAlgorithms.java:395)
        at org.spongycastle.math.ec.ECAlgorithms.sumOfTwoMultiplies(ECAlgorithms.java:90)
        at org.spongycastle.crypto.signers.ECDSASigner.verifySignature(ECDSASigner.java:162)
        at io.scalechain.crypto.ECKey.verify(ECKey.java:37)
        at io.scalechain.blockchain.script.ops.CheckSig$class.checkSig(Crypto.scala:186)
        at io.scalechain.blockchain.script.ops.OpCheckSig.execute(Crypto.scala:333)
...
```
## solution
1. Move RPC operations out of actors. 
2. In the future, we may have to come up with worker pool, which has workers that do costly operations such as transaction validations.

**Comment by Kangmo** [comment]
code pushed. 44435c34cfd41cc1f790aa49912c06d971a87ad8
