### ISSUE TITLE
Inconsistency in wallet database block height pointing to detached blocks

### ISSUE THREAD

**Issue by Kangmo** [ScaleChain/scalachain#85]
## Problem

After block reorganization, we hit an assertion at io.scalechain.wallet.Wallet.getConfirmations(Wallet.scala:479)

```
10:20:25.136 [nioEventLoopGroup-3-4] WARN  i.s.blockchain.chain.Blockchain - Block reorganization started. Original Best : (Hash(bytes("0c5b3bfaae7d02ae77ee3e43287ef88ca7183f355b046f577327e991e1c2b819")),BlockInfo(107,68719483616,None,1,0,BlockHeader(version=1, hashPrevBlock=Hash(bytes("0940412b1cde69ffb2e395edc55b2c5d8423359969c7e04280402bc2ecbcf21e")), hashMerkleRoot=Hash(bytes("9680a287d16e65cd9d3213272090eb7f555517e8c04215d1b0e4c09d4cda66a8")), timestamp=1467422424L, target=10L, nonce=608L),Some(FileRecordLocator(0,RecordLocator(46129,173))))), The new Best (Hash(bytes("00021a5d7548f3da87a36b945187842ff0cf6dbce128c3721bf389ed95ebf4fc")),BlockInfo(42,68719495344,None,1,0,BlockHeader(version=1, hashPrevBlock=Hash(bytes("0eebd27db3c5308fdcff06713f72912aab9358128c394c85a9f6602eb80806cc")), hashMerkleRoot=Hash(bytes("2f70491daca89f70abafc7bba9a687d6781b66c8cc4b53f435f0266b31f0b9b5")), timestamp=1467422425L, target=10L, nonce=523L),Some(FileRecordLocator(0,RecordLocator(46648,173)))))


....

10:20:26.725 [nioEventLoopGroup-5-7] INFO  i.s.blockchain.api.RequestHandler$ - String Request : {"id":1467422426723,"method":"listunspent","params":[0,9999999,["moFX2hLQxWopV6dPuhM5pUoZK4PfTQm4fc"]]}
10:20:26.729 [nioEventLoopGroup-5-7] ERROR io.scalechain.wallet.Wallet - best=47 blockHeight= 68
10:20:26.730 [nioEventLoopGroup-3-4] INFO  i.s.b.n.handler.BlockMessageHandler$ - [P2P] Received a block. Hash : Hash(bytes("0bdd291af35b0c9c7498bcf0d1bdbaf0fc931ba397a229cab72c2054e485b8e7")), Header : BlockHeader(version=1, hashPrevBlock=Hash(bytes("0866676daa0f40286ff567c41731ea3ed631b1e80dfa1196882831920036b0fc")), hashMerkleRoot=Hash(bytes("9c4253d74500bd872f1fb3d554c68063c7ca98a042c38bb3d82b47eda0306fd4")), timestamp=1467422426L, target=10L, nonce=620L)
10:20:26.730 [nioEventLoopGroup-5-7] ERROR i.s.b.api.http.ApiServerHandler - java.lang.AssertionError: assertion failed. Stack : java.lang.AssertionError: assertion failed
        at scala.Predef$.assert(Predef.scala:156)
        at io.scalechain.wallet.Wallet.getConfirmations(Wallet.scala:479)
        at io.scalechain.wallet.Wallet$$anonfun$7.apply$mcJJ$sp(Wallet.scala:450)
        at io.scalechain.wallet.Wallet$$anonfun$7.apply(Wallet.scala:450)
        at io.scalechain.wallet.Wallet$$anonfun$7.apply(Wallet.scala:450)
        at scala.Option.map(Option.scala:146)
        at io.scalechain.wallet.Wallet.getUnspentCoinDescription(Wallet.scala:450)
        at io.scalechain.wallet.Wallet$$anonfun$listUnspent$1$$anonfun$apply$3.apply(Wallet.scala:527)
        at io.scalechain.wallet.Wallet$$anonfun$listUnspent$1$$anonfun$apply$3.apply(Wallet.scala:526)
        at scala.collection.immutable.List.map(List.scala:273)
        at io.scalechain.wallet.Wallet$$anonfun$listUnspent$1.apply(Wallet.scala:526)
        at io.scalechain.wallet.Wallet$$anonfun$listUnspent$1.apply(Wallet.scala:522)
        at scala.collection.immutable.List.flatMap(List.scala:327)
        at io.scalechain.wallet.Wallet.listUnspent(Wallet.scala:522)
        at io.scalechain.blockchain.api.command.wallet.ListUnspent$$anonfun$invoke$1.apply(ListUnspent.scala:85)
        at io.scalechain.blockchain.api.command.wallet.ListUnspent$$anonfun$invoke$1.apply(ListUnspent.scala:76)
        at io.scalechain.blockchain.api.command.RpcCommand$class.handlingException(RpcCommand.scala:16)

```

Also, a transaction output is marked unspent many times.

```
10:20:25.842 [nioEventLoopGroup-3-4] INFO  io.scalechain.wallet.Wallet - [Wallet unregister tx:Hash(bytes("d9c3030c10916edd939e1d60c3d6ce11081fb65a82504d4a59addeb4464be197"))] set output unspent. outpoint : OutPoint(Hash(bytes("fc6a7361be06cd59ae1b7500f072effc3abef44c81d4dcc1acd3d40b7f7f6313")),0), inputIndex : 0
10:20:25.842 [nioEventLoopGroup-3-4] INFO  io.scalechain.wallet.Wallet - [Wallet unregister tx:Hash(bytes("d9c3030c10916edd939e1d60c3d6ce11081fb65a82504d4a59addeb4464be197"))] set output unspent. outpoint : OutPoint(Hash(bytes("fc6a7361be06cd59ae1b7500f072effc3abef44c81d4dcc1acd3d40b7f7f6313")),0), inputIndex : 010:20:25.842 [nioEventLoopGroup-3-4] INFO  io.scalechain.wallet.Wallet - [Wallet unregister tx:Hash(bytes("d9c3030c10916edd939e1d60c3d6ce11081fb65a82504d4a59addeb4464be197"))] set output unspent. outpoint : OutPoint(Hash(bytes("fc6a7361be06cd59ae1b7500f072effc3abef44c81d4dcc1acd3d40b7f7f6313")),0), inputIndex : 010:20:25.843 [nioEventLoopGroup-3-4] INFO  io.scalechain.wallet.Wallet - [Wallet unregister tx:Hash(bytes("d9c3030c10916edd939e1d60c3d6ce11081fb65a82504d4a59addeb4464be197"))] set output unspent. outpoint : OutPoint(Hash(bytes("fc6a7361be06cd59ae1b7500f072effc3abef44c81d4dcc1acd3d40b7f7f6313")),0), inputIndex : 010:20:25.843 [nioEventLoopGroup-3-4] INFO  io.scalechain.wallet.Wallet - [Wallet unregister tx:Hash(bytes("d9c3030c10916edd939e1d60c3d6ce11081fb65a82504d4a59addeb4464be197"))] set output unspent. outpoint : OutPoint(Hash(bytes("fc6a7361be06cd59ae1b7500f072effc3abef44c81d4dcc1acd3d40b7f7f6313")),0), inputIndex : 010:20:25.844 [nioEventLoopGroup-3-4] INFO  io.scalechain.wallet.Wallet - [Wallet unregister tx:Hash(bytes("d9c3030c10916edd939e1d60c3d6ce11081fb65a82504d4a59addeb4464be197"))] set output unspent. outpoint : OutPoint(Hash(bytes("fc6a7361be06cd59ae1b7500f072effc3abef44c81d4dcc1acd3d40b7f7f6313")),0), inputIndex : 010:20:25.844 [nioEventLoopGroup-3-4] INFO  io.scalechain.wallet.Wallet - [Wallet unregister tx:Hash(bytes("d9c3030c10916edd939e1d60c3d6ce11081fb65a82504d4a59addeb4464be197"))] set output unspent. outpoint : OutPoint(Hash(bytes("fc6a7361be06cd59ae1b7500f072effc3abef44c81d4dcc1acd3d40b7f7f6313")),0), inputIndex : 010:20:25.845 [nioEventLoopGroup-3-4] INFO  io.scalechain.wallet.Wallet - [Wallet unregister tx:Hash(bytes("d9c3030c10916edd939e1d60c3d6ce11081fb65a82504d4a59addeb4464be197"))] set output unspent. outpoint : OutPoint(Hash(bytes("fc6a7361be06cd59ae1b7500f072effc3abef44c81d4dcc1acd3d40b7f7f6313")),0), inputIndex : 0
```
## Root cause

The Wallet.unregisterTranasction method loops based on the outputOwnerships. Also, checking if an output ownership owns each transaction output of the transaction to unregister is error-prone.
## Solution

Make the code simpler by completely removing the related data for the transaction in the wallet instead of checking if each output is owned by ownput ownerships.

**Comment by Kangmo** [comment]
Done
